"""
Export Bundle Generator
Creates regulator-ready compliance packages (ZIP/PDF) for
audit requests, consumer disclosure, or legal proceedings.
"""

import zipfile
import io
import json
from datetime import datetime
from typing import List, Optional, Dict, Any
from pathlib import Path

from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch


class ExportBundle:
    """Compliance bundle for delivery to regulators or consumers."""
    
    def __init__(self, organization_id: str, generated_by: str):
        self.organization_id = organization_id
        self.generated_by = generated_by
        self.generated_at = datetime.utcnow()
        self.bundle_id = f"BUNDLE-{organization_id}-{self.generated_at.strftime('%Y%m%d-%H%M%S')}"
        self.contents: List[Dict[str, Any]] = []
    
    def add_section(
        self,
        title: str,
        content: bytes,
        content_type: str,
        filename: str,
        metadata: Optional[Dict] = None
    ):
        """Add a document section to the bundle."""
        self.contents.append({
            'title': title,
            'content': content,
            'content_type': content_type,
            'filename': filename,
            'metadata': metadata or {},
            'added_at': datetime.utcnow().isoformat()
        })
    
    def generate_zip(self) -> bytes:
        """Generate ZIP archive of all bundle contents."""
        zip_buffer = io.BytesIO()
        
        with zipfile.ZipFile(zip_buffer, 'w', zipfile.ZIP_DEFLATED) as zf:
            # Manifest
            manifest = {
                'bundle_id': self.bundle_id,
                'generated_at': self.generated_at.isoformat(),
                'generated_by': self.generated_by,
                'organization_id': self.organization_id,
                'sections': [
                    {
                        'title': c['title'],
                        'filename': c['filename'],
                        'content_type': c['content_type'],
                        'metadata': c['metadata']
                    }
                    for c in self.contents
                ]
            }
            zf.writestr('manifest.json', json.dumps(manifest, indent=2))
            
            # Content files
            for item in self.contents:
                zf.writestr(item['filename'], item['content'])
        
        zip_buffer.seek(0)
        return zip_buffer.read()
    
    def generate_pdf_summary(self) -> bytes:
        """Generate human-readable PDF summary of bundle contents."""
        buffer = io.BytesIO()
        doc = SimpleDocTemplate(
            buffer,
            pagesize=letter,
            rightMargin=72,
            leftMargin=72,
            topMargin=72,
            bottomMargin=18
        )
        
        styles = getSampleStyleSheet()
        story = []
        
        # Header
        title_style = ParagraphStyle(
            'CustomTitle',
            parent=styles['Heading1'],
            fontSize=24,
            spaceAfter=30,
            textColor=colors.HexColor('#1e3a5f')
        )
        story.append(Paragraph("MHMDA Compliance Export", title_style))
        story.append(Spacer(1, 20))
        
        # Metadata table
        metadata_data = [
            ['Bundle ID:', self.bundle_id],
            ['Generated:', self.generated_at.strftime('%Y-%m-%d %H:%M UTC')],
            ['Generated By:', self.generated_by],
            ['Organization:', self.organization_id],
        ]
        
        metadata_table = Table(metadata_data, colWidths=[2*inch, 4*inch])
        metadata_table.setStyle(TableStyle([
            ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, -1), 10),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 12),
        ]))
        story.append(metadata_table)
        story.append(Spacer(1, 30))
        
        # Contents section
        story.append(Paragraph("Bundle Contents", styles['Heading2']))
        story.append(Spacer(1, 12))
        
        for i, item in enumerate(self.contents, 1):
            story.append(Paragraph(f"{i}. {item['title']}", styles['Heading3']))
            story.append(Paragraph(f"Filename: {item['filename']}", styles['Normal']))
            story.append(Paragraph(f"Type: {item['content_type']}", styles['Normal']))
            
            if item['metadata']:
                meta_text = "<br/>".join([f"<b>{k}:</b> {v}" for k, v in item['metadata'].items()])
                story.append(Paragraph(f"Metadata: {meta_text}", styles['Normal']))
            
            story.append(Spacer(1, 12))
        
        # Legal footer
        story.append(Spacer(1, 40))
        footer_style = ParagraphStyle(
            'Footer',
            parent=styles['Normal'],
            fontSize=8,
            textColor=colors.grey
        )
        story.append(Paragraph(
            f"This document was generated by Health Data Ready on {self.generated_at.strftime('%Y-%m-%d')}. "
            "This export is provided for compliance purposes under Washington State's My Health My Data Act (RCW 19.373). "
            "Consult qualified legal counsel before submission to regulatory authorities.",
            footer_style
        ))
        
        doc.build(story)
        buffer.seek(0)
        return buffer.read()


class BundleGenerator:
    """Factory for common bundle types."""
    
    @staticmethod
    def create_consumer_disclosure_bundle(
        organization_id: str,
        consumer_name: str,
        data_elements: List[Dict],
        processing_purposes: List[str],
        third_parties: List[Dict],
        generated_by: str
    ) -> ExportBundle:
        """
        Create disclosure bundle for consumer's data access request.
        Per RCW 19.373.120 - Consumer's right to confirm processing.
        """
        bundle = ExportBundle(organization_id, generated_by)
        
        # JSON machine-readable data
        disclosure_data = {
            'consumer_name': consumer_name,
            'disclosure_date': datetime.utcnow().isoformat(),
            'organization_id': organization_id,
            'data_elements': data_elements,
            'processing_purposes': processing_purposes,
            'third_party_disclosures': third_parties,
            'consumer_rights': {
                'access': 'Right to confirm processing (RCW 19.373.120)',
                'deletion': 'Right to delete (RCW 19.373.130)',
                'withdraw_consent': 'Right to withdraw consent (RCW 19.373.140)',
                'appeal': 'Right to appeal (RCW 19.373.150)'
            }
        }
        
        bundle.add_section(
            title="Machine-Readable Data Export",
            content=json.dumps(disclosure_data, indent=2).encode('utf-8'),
            content_type="application/json",
            filename="consumer_data.json",
            metadata={'format_version': '1.0', 'standard': 'MHMDA'}
        )
        
        # Human-readable summary PDF
        pdf_content = BundleGenerator._create_disclosure_pdf(
            consumer_name, data_elements, processing_purposes, third_parties
        )
        
        bundle.add_section(
            title="Privacy Report",
            content=pdf_content,
            content_type="application/pdf",
            filename="privacy_report.pdf",
            metadata={'pages': BundleGenerator._count_pdf_pages(pdf_content)}
        )
        
        return bundle
    
    @staticmethod
    def create_regulatory_audit_bundle(
        organization_id: str,
        audit_period_start: datetime,
        audit_period_end: datetime,
        data_inventory: List[Dict],
        rights_requests: List[Dict],
        policy_documents: List[Dict],
        evidence_records: List[Dict],
        generated_by: str
    ) -> ExportBundle:
        """
        Create comprehensive audit bundle for regulatory examination.
        """
        bundle = ExportBundle(organization_id, generated_by)
        
        # Executive summary
        summary = {
            'audit_period': {
                'start': audit_period_start.isoformat(),
                'end': audit_period_end.isoformat()
            },
            'metrics': {
                'total_data_elements': len(data_inventory),
                'total_rights_requests': len(rights_requests),
                'requests_by_status': BundleGenerator._count_by_status(rights_requests),
                'avg_response_days': BundleGenerator._calculate_avg_response(rights_requests)
            },
            'policies_in_effect': [p['title'] for p in policy_documents],
            'evidence_items': len(evidence_records)
        }
        
        bundle.add_section(
            title="Audit Summary",
            content=json.dumps(summary, indent=2).encode('utf-8'),
            content_type="application/json",
            filename="00-executive-summary.json",
            metadata={'type': 'summary'}
        )
        
        # Full data inventory
        bundle.add_section(
            title="Data Inventory",
            content=json.dumps(data_inventory, indent=2).encode('utf-8'),
            content_type="application/json",
            filename="01-data-inventory.json",
            metadata={'records': len(data_inventory)}
        )
        
        # Rights request log
        bundle.add_section(
            title="Consumer Rights Requests",
            content=json.dumps(rights_requests, indent=2).encode('utf-8'),
            content_type="application/json",
            filename="02-rights-requests.json",
            metadata={'records': len(rights_requests)}
        )
        
        # Policies
        for policy in policy_documents:
            bundle.add_section(
                title=policy['title'],
                content=policy['content'].encode('utf-8'),
                content_type="text/markdown",
                filename=f"03-policy-{policy['id']}.md",
                metadata={'version': policy.get('version'), 'effective_date': policy.get('effective_date')}
            )
        
        return bundle
    
    @staticmethod
    def _create_disclosure_pdf(consumer_name, data_elements, purposes, third_parties) -> bytes:
        """Generate PDF disclosure document."""
        buffer = io.BytesIO()
        doc = SimpleDocTemplate(buffer, pagesize=letter)
        styles = getSampleStyleSheet()
        story = []
        
        story.append(Paragraph(f"Privacy Disclosure for {consumer_name}", styles['Title']))
        story.append(Spacer(1, 20))
        
        story.append(Paragraph("Data Elements Collected:", styles['Heading2']))
        for element in data_elements:
            story.append(Paragraph(f"• {element['name']} ({element['category']})", styles['Normal']))
        
        story.append(Paragraph("Processing Purposes:", styles['Heading2']))
        for purpose in purposes:
            story.append(Paragraph(f"• {purpose}", styles['Normal']))
        
        story.append(Paragraph("Third Party Disclosures:", styles['Heading2']))
        for party in third_parties:
            story.append(Paragraph(f"• {party['name']} - {party['purpose']}", styles['Normal']))
        
        doc.build(story)
        buffer.seek(0)
        return buffer.read()
    
    @staticmethod
    def _count_pdf_pages(content: bytes) -> int:
        """Count pages in PDF content."""
        # Simplified: count /Type /Page occurrences
        return content.count(b'/Type /Page')
    
    @staticmethod
    def _count_by_status(requests: List[Dict]) -> Dict[str, int]:
        """Count requests by status."""
        counts = {}
        for r in requests:
            status = r.get('status', 'unknown')
            counts[status] = counts.get(status, 0) + 1
        return counts
    
    @staticmethod
    def _calculate_avg_response(requests: List[Dict]) -> Optional[float]:
        """Calculate average response time in days."""
        completed = [r for r in requests if r.get('completed_at') and r.get('received_at')]
        if not completed:
            return None
        
        total_days = 0
        for r in completed:
            received = datetime.fromisoformat(r['received_at'])
            completed_date = datetime.fromisoformat(r['completed_at'])
            total_days += (completed_date - received).days
        
        return round(total_days / len(completed), 1)
